services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db_chefchoice
    environment:
      - POSTGRES_DB=chefchoice
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  backend:
    image: 'chefchioce-backend-image:latest'
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DB_PATH}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true

  frontend:
    image: 'chefchioce-frontend-image:latest'
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_HOST=backend

